build:
  environment:
    php:
      version: "7.4"
  nodes:
    coverage:
      tests:
        override:
          - command: composer phpunit-xml
            coverage:
              file: phpunit.xml
              format: clover
    analysis:
      tests:
        override:
          - php-scrutinizer-run